# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Thymeleaf off (not using it)
spring.thymeleaf.enabled=false

# Context path (optional)
server.port=8181
server.servlet.context-path=/

# No need for extra resource handler — Spring Boot serves from static/
spring.mvc.static-path-pattern=/**
